### ISSUE TITLE
投稿报错

### ISSUE THREAD

**Issue by aipiao-gh** [NLR-DevTeam/GrassPictures#2]
2023-02-11 10:17:19 W/草图插件: Exception in executing command `[mirai:source:ids=[164576], internalIds=[-331462555], from group 3291584316 to 182850795 at 1676081839][mirai:quote:[mirai:source:ids=[164574], internalIds=[294937614], from 3466938657 to 182850795 at 1676081805], content=<not yet initialized>] 草图投稿`
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:258)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:219)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage$suspendImpl(CommandSender.kt:687)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage(CommandSender.kt)
        at net.mamoe.mirai.console.command.MemberCommandSender$sendMessage$4.invoke(CommandSender.kt)
        at net.mamoe.mirai.console.command.MemberCommandSender$sendMessage$4.invoke(CommandSender.kt)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)
        at net.mamoe.mirai.console.command.MemberCommandSender.sendMessage(CommandSender.kt)
        at GrassPictures-1.1.9.mirai2.jar//cn.whitrayhb.grasspics.commands.PostGrassPic.onCommand(PostGrassPic.java:209)
        at net.mamoe.mirai.console.command.java.JRawCommand$overloads$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by XIAYM-gh** [comment]
小概率事件 + 未缓存图片消息即使try-catch了错误也无法获取图片内容
Close as not planned
