### ISSUE TITLE
草图服务失效，获取草图时返回“您指定的图片不存在!”，投稿草图时报错

### ISSUE THREAD

**Issue by QSlotus** [NLR-DevTeam/GrassPictures#3]
重启过，问题没有解决。
***
如题。
具体情况如图所示：
![IMG_20230430_133308](https://user-images.githubusercontent.com/109905194/235337365-54fd93fa-161e-4251-b245-3ca0c1acf6af.jpg)

后台输出显示：（个人信息已作处理）
```
2023-04-30 13:32:57 V/Bot.xxxxxxxxxx: [Bot(xxxxxxxxxx)] 秋水(xxxxxxxxxx) -> 生草
2023-04-30 13:32:59 V/Bot.xxxxxxxxxx: Group(xxxxxxxxxx) <- [mirai:quote:[mirai:source:ids=[100926], internalIds=[370393661], from group xxxxxxxxxx to xxxxxxxxxx at 1682832777], content=生草]您指定的图片不存在!
```
并没有“图片下载失败”之类的报错

经过咨询相关人员后得知，机器人并未被ban或者被限流

同时机器人的草图投稿功能也出现了问题，如图所示：
![IMG_20230430_134036](https://user-images.githubusercontent.com/109905194/235337570-58a25e67-118d-46b3-8457-68c0f86a3a5d.jpg)

控制台输出：
```
2023-04-30 13:41:26 W/stderr: org.json.JSONException: Expected a ',' or '}' at 11 [character 12 line 1]
2023-04-30 13:41:26 W/stderr:   at GrassPictures-1.2.0.mirai2.jar[private]//org.json.JSONTokener.syntaxError(JSONTokener.java:501)
2023-04-30 13:41:26 W/stderr:   at GrassPictures-1.2.0.mirai2.jar[private]//org.json.JSONObject.<init>(JSONObject.java:264)
2023-04-30 13:41:26 W/stderr:   at GrassPictures-1.2.0.mirai2.jar[private]//org.json.JSONObject.<init>(JSONObject.java:404)
2023-04-30 13:41:26 W/stderr:   at GrassPictures-1.2.0.mirai2.jar//cn.whitrayhb.grasspics.commands.PostGrassPic.lambda$postToPublicChannel$1(PostGrassPic.java:92)
2023-04-30 13:41:26 W/stderr:   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-04-30 13:41:26 W/stderr:   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-04-30 13:41:26 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-30 13:41:26 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-30 13:41:26 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by XIAYM-gh** [comment]
接口返回问题，并非草图插件错误，请手动访问 api 地址查看是否返回正确的 JSON 数据
以及 1.2.1 版本有了更详细的错误码解析，你可以升级一下

*Closes this issue*

**Comment by QSlotus** [comment]
好捏

**Comment by XIAYM-gh** [comment]
正在上传 release
